export const products = [
  {
    id: "1",
    name: "Gargantilla de oso",
    imageSrc: "/img/collares/collar1.webp",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 150,
  },
  {
    id: "2",
    name: "Gargantilla Mariposa",
    imageSrc: "/img/collares/collar2.webp",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
  {
    id: "3",
    name: "Gargantilla Blanca",
    imageSrc: "/img/collares/collar4.webp",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
  {
    id: "4",
    name: "Pulsera del mar",
    imageSrc: "/img/Pulseras/p1.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
  {
    id: "5",
    name: "Pulsera Arcoiris",
    imageSrc: "/img/Pulseras/p2.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
  {
    id: "6",
    name: "Pulsera de la Distancia",
    imageSrc: "/img/Pulseras/p3.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
  {
    id: "7",
    name: "Pulsera de Promesa",
    imageSrc: "/img/Pulseras/p4.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
  {
    id: "8",
    name: "Pulsera de Estrellas",
    imageSrc: "/img/Pulseras/p5.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
];

export const lienzos = [
  {
    id: "1",
    colection: "Colección: Personalización",
    imageSrc: "/img/Target/t1.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
    style: "Vectorización",
    dimensions: "18cm x 24cm",
  },
  {
    id: "2",
    colection: "Colección: Spiderman",
    imageSrc: "/img/carrusel/retrato2.webp",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
    style: "Vectorización",
    dimensions: "18cm x 24cm",
  },
  {
    id: "3",
    colection: "Colección: Personalización",
    imageSrc: "/img/Target/t3.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
    style: "Vectorización",
    dimensions: "90cm x 90cm",
  },
  {
    id: "4",
    colection: "Colección: Personalidad",
    imageSrc: "/img/Target/t4.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
    style: "Retrato",
    dimensions: "18cm x 24cm",
  },
  {
    id: "5",
    colection: "Colección: Cantantes",
    imageSrc: "/img/Target/t5.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
    style: "Retrato",
    dimensions: "18cm x 24cm",
  },
  {
    id: "6",
    colection: "Colección: Personalización",
    imageSrc: "/img/Target/t7.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
    style: "Retrato",
    dimensions: "18cm x 24cm",
  },
  {
    id: "7",
    colection: "Colección: Hakuna Matata",
    imageSrc: "/img/Target/t6.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
    style: "Vectorización",
    dimensions: "18cm x 24cm",
  },
  {
    id: "8",
    colection: "Colección: Mascotas",
    imageSrc: "/img/Target/t8.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
    style: "Animado",
    dimensions: "50cm x 50cm",
  },
  {
    id: "9",
    colection: "Colección: Cantantes",
    imageSrc: "/img/Target/t9.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
    style: "Vectorización",
    dimensions: "18cm x 24cm",
  },
];

export const covers = [
  {
    id: "1",
    name: "Mascotas - Para todos los móviles",
    description: "Personaliza tus covers con tu mejores recuerdos",
    imageSrc: "/img/covers/c1.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
  {
    id: "2",
    name: "Retratos - Para todos los móviles",
    description: "Brinda el mejor estilo a tu cover con nosotros",
    imageSrc: "/img/covers/c3.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
  {
    id: "3",
    name: "Deportes - Para todos los móviles",
    description: '"Si vas paso a paso y con confianza, puedes llegar lejos"',
    imageSrc: "/img/covers/c4.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
  {
    id: "4",
    name: "Haikyuu - Para todos los móviles",
    description:
      "Si antes era tu mayor oponente, ahora es tu formidable aliado",
    imageSrc: "/img/covers/cover2.webp",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
];

export const publicidad = [
  {
    id: "1",
    name: "Afiche Institucional",
    description:
      "Lleva tus volantes instucionales con la esencia de tu negocio",
    imageSrc: "/img/pub/pub1.png",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
  {
    id: "2",
    name: "Afiche Promocional",
    description: "Brinda las mejores campañas publicitarias",
    imageSrc: "/img/pub/pub2.png",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
  {
    id: "3",
    name: "Afiche Publicitarios",
    description: "Brinda campañas promocionales con tu propio estilo",
    imageSrc: "/img/pub/pub3.png",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
  {
    id: "4",
    name: "Ramos de girasoles",
    description:
      "Un detalle increíblemente sencillo, para una persona sencillamente increíble.",
    imageSrc: "/img/ramos/r1.jpeg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
  {
    id: "5",
    name: "Ramos de Rosa",
    description:
      "Deseo que esta rosa te llene de alegría y de amor, y que cada vez que la veas recuerdes que siempre estaré aquí para ti.",
    imageSrc: "/img/ramos/r2.jpeg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
  {
    id: "6",
    name: "Spotify",
    description: '"Hay una canción para cada emoción"',
    imageSrc: "/img/Spotify/s1.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 135,
  },
];
